### ISSUE TITLE
`bias_correction.XBiasCorrection` does not import after installing via `pip`

### ISSUE THREAD

**Issue by aaronspring** [pankajkarman/bias_correction#6]
Hi @pankajkarman, thanks for this nice code. I especially like the `xr.apply_ufunc` capabilities. 

However, I noticed that `XBiasCorrection` does not import when installing via `pip`:

![image](https://user-images.githubusercontent.com/12237157/126760351-acb109ac-47c8-4885-a77f-8d14470e09c3.png)

I and students from the ASP summer school https://asp.ucar.edu/asp-colloquia want to use your code for bias reduction and to then compute skill with climpred https://github.com/pangeo-data/climpred. Some quantile mapping is required for precip.

(So far I just copied https://github.com/pankajkarman/bias_correction/blob/master/bias_correction.py into climpred in the PR below, but I'd prefer to just add `bias-correction` to the requirements).

PR how to integrate this into climpred: https://github.com/pangeo-data/climpred/pull/638

**Comment by pankajkarman** [comment]
Hi @aaronspring, thank you very much for pointing out this issue. 
You got this issue because the latest version of the repository was not uploaded to pypi. I have updated it there now.
